/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.zhuyb.graphbatis.jooq.DefaultSchema;
import org.zhuyb.graphbatis.jooq.Indexes;
import org.zhuyb.graphbatis.jooq.Keys;
import org.zhuyb.graphbatis.jooq.tables.records.TRoomRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TRoom extends TableImpl<TRoomRecord> {

    /**
     * The reference instance of <code>t_room</code>
     */
    public static final TRoom T_ROOM = new TRoom();
    private static final long serialVersionUID = 216191959;
    /**
     * The column <code>t_room.room_id</code>.
     */
    public final TableField<TRoomRecord, Integer> ROOM_ID = createField(DSL.name("room_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");
    /**
     * The column <code>t_room.room_name</code>.
     */
    public final TableField<TRoomRecord, String> ROOM_NAME = createField(DSL.name("room_name"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>t_room</code> table reference
     */
    public TRoom() {
        this(DSL.name("t_room"), null);
    }

    /**
     * Create an aliased <code>t_room</code> table reference
     */
    public TRoom(String alias) {
        this(DSL.name(alias), T_ROOM);
    }

    /**
     * Create an aliased <code>t_room</code> table reference
     */
    public TRoom(Name alias) {
        this(alias, T_ROOM);
    }

    private TRoom(Name alias, Table<TRoomRecord> aliased) {
        this(alias, aliased, null);
    }

    private TRoom(Name alias, Table<TRoomRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TRoom(Table<O> child, ForeignKey<O, TRoomRecord> key) {
        super(child, key, T_ROOM);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRoomRecord> getRecordType() {
        return TRoomRecord.class;
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_ROOM_PRIMARY);
    }

    @Override
    public Identity<TRoomRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_ROOM;
    }

    @Override
    public UniqueKey<TRoomRecord> getPrimaryKey() {
        return Keys.KEY_T_ROOM_PRIMARY;
    }

    @Override
    public List<UniqueKey<TRoomRecord>> getKeys() {
        return Arrays.<UniqueKey<TRoomRecord>>asList(Keys.KEY_T_ROOM_PRIMARY);
    }

    @Override
    public TRoom as(String alias) {
        return new TRoom(DSL.name(alias), this);
    }

    @Override
    public TRoom as(Name alias) {
        return new TRoom(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRoom rename(String name) {
        return new TRoom(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRoom rename(Name name) {
        return new TRoom(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
