/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.zhuyb.graphbatis.jooq.DefaultSchema;
import org.zhuyb.graphbatis.jooq.Indexes;
import org.zhuyb.graphbatis.jooq.Keys;
import org.zhuyb.graphbatis.jooq.tables.records.TSubjectRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TSubject extends TableImpl<TSubjectRecord> {

    /**
     * The reference instance of <code>t_subject</code>
     */
    public static final TSubject T_SUBJECT = new TSubject();
    private static final long serialVersionUID = -39692680;
    /**
     * The column <code>t_subject.subject_id</code>.
     */
    public final TableField<TSubjectRecord, Integer> SUBJECT_ID = createField(DSL.name("subject_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");
    /**
     * The column <code>t_subject.subject_name</code>.
     */
    public final TableField<TSubjectRecord, String> SUBJECT_NAME = createField(DSL.name("subject_name"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>t_subject</code> table reference
     */
    public TSubject() {
        this(DSL.name("t_subject"), null);
    }

    /**
     * Create an aliased <code>t_subject</code> table reference
     */
    public TSubject(String alias) {
        this(DSL.name(alias), T_SUBJECT);
    }

    /**
     * Create an aliased <code>t_subject</code> table reference
     */
    public TSubject(Name alias) {
        this(alias, T_SUBJECT);
    }

    private TSubject(Name alias, Table<TSubjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private TSubject(Name alias, Table<TSubjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TSubject(Table<O> child, ForeignKey<O, TSubjectRecord> key) {
        super(child, key, T_SUBJECT);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TSubjectRecord> getRecordType() {
        return TSubjectRecord.class;
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_SUBJECT_PRIMARY);
    }

    @Override
    public Identity<TSubjectRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_SUBJECT;
    }

    @Override
    public UniqueKey<TSubjectRecord> getPrimaryKey() {
        return Keys.KEY_T_SUBJECT_PRIMARY;
    }

    @Override
    public List<UniqueKey<TSubjectRecord>> getKeys() {
        return Arrays.<UniqueKey<TSubjectRecord>>asList(Keys.KEY_T_SUBJECT_PRIMARY);
    }

    @Override
    public TSubject as(String alias) {
        return new TSubject(DSL.name(alias), this);
    }

    @Override
    public TSubject as(Name alias) {
        return new TSubject(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TSubject rename(String name) {
        return new TSubject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TSubject rename(Name name) {
        return new TSubject(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
