/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.zhuyb.graphbatis.jooq.tables.TStudent;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TStudentRecord extends UpdatableRecordImpl<TStudentRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1858723538;

    /**
     * Create a detached TStudentRecord
     */
    public TStudentRecord() {
        super(TStudent.T_STUDENT);
    }

    /**
     * Create a detached, initialised TStudentRecord
     */
    public TStudentRecord(Integer studentId, Integer roomId, String studentName) {
        super(TStudent.T_STUDENT);

        set(0, studentId);
        set(1, roomId);
        set(2, studentName);
    }

    /**
     * Getter for <code>t_student.student_id</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>t_student.student_id</code>.
     */
    public TStudentRecord setStudentId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>t_student.room_id</code>.
     */
    public Integer getRoomId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>t_student.room_id</code>.
     */
    public TStudentRecord setRoomId(Integer value) {
        set(1, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>t_student.student_name</code>.
     */
    @Size(max = 50)
    public String getStudentName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>t_student.student_name</code>.
     */
    public TStudentRecord setStudentName(String value) {
        set(2, value);
        return this;
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TStudent.T_STUDENT.STUDENT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return TStudent.T_STUDENT.ROOM_ID;
    }

    @Override
    public Field<String> field3() {
        return TStudent.T_STUDENT.STUDENT_NAME;
    }

    @Override
    public Integer component1() {
        return getStudentId();
    }

    @Override
    public Integer component2() {
        return getRoomId();
    }

    @Override
    public String component3() {
        return getStudentName();
    }

    @Override
    public Integer value1() {
        return getStudentId();
    }

    @Override
    public Integer value2() {
        return getRoomId();
    }

    @Override
    public String value3() {
        return getStudentName();
    }

    @Override
    public TStudentRecord value1(Integer value) {
        setStudentId(value);
        return this;
    }

    @Override
    public TStudentRecord value2(Integer value) {
        setRoomId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public TStudentRecord value3(String value) {
        setStudentName(value);
        return this;
    }

    @Override
    public TStudentRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
