/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.zhuyb.graphbatis.jooq.tables.TTeacher;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TTeacherRecord extends UpdatableRecordImpl<TTeacherRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1450669830;

    /**
     * Create a detached TTeacherRecord
     */
    public TTeacherRecord() {
        super(TTeacher.T_TEACHER);
    }

    /**
     * Create a detached, initialised TTeacherRecord
     */
    public TTeacherRecord(Integer teacherId, String teacherName, Integer subjectId) {
        super(TTeacher.T_TEACHER);

        set(0, teacherId);
        set(1, teacherName);
        set(2, subjectId);
    }

    /**
     * Getter for <code>t_teacher.teacher_id</code>.
     */
    public Integer getTeacherId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>t_teacher.teacher_id</code>.
     */
    public TTeacherRecord setTeacherId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>t_teacher.teacher_name</code>.
     */
    @Size(max = 50)
    public String getTeacherName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>t_teacher.teacher_name</code>.
     */
    public TTeacherRecord setTeacherName(String value) {
        set(1, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>t_teacher.subject_id</code>.
     */
    public Integer getSubjectId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>t_teacher.subject_id</code>.
     */
    public TTeacherRecord setSubjectId(Integer value) {
        set(2, value);
        return this;
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TTeacher.T_TEACHER.TEACHER_ID;
    }

    @Override
    public Field<String> field2() {
        return TTeacher.T_TEACHER.TEACHER_NAME;
    }

    @Override
    public Field<Integer> field3() {
        return TTeacher.T_TEACHER.SUBJECT_ID;
    }

    @Override
    public Integer component1() {
        return getTeacherId();
    }

    @Override
    public String component2() {
        return getTeacherName();
    }

    @Override
    public Integer component3() {
        return getSubjectId();
    }

    @Override
    public Integer value1() {
        return getTeacherId();
    }

    @Override
    public String value2() {
        return getTeacherName();
    }

    @Override
    public Integer value3() {
        return getSubjectId();
    }

    @Override
    public TTeacherRecord value1(Integer value) {
        setTeacherId(value);
        return this;
    }

    @Override
    public TTeacherRecord value2(String value) {
        setTeacherName(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public TTeacherRecord value3(Integer value) {
        setSubjectId(value);
        return this;
    }

    @Override
    public TTeacherRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
