/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables.daos;


import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.zhuyb.graphbatis.jooq.tables.TRoom;
import org.zhuyb.graphbatis.jooq.tables.records.TRoomRecord;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Repository
public class TRoomDao extends DAOImpl<TRoomRecord, org.zhuyb.graphbatis.jooq.tables.pojos.TRoom, Integer> {

    /**
     * Create a new TRoomDao without any configuration
     */
    public TRoomDao() {
        super(TRoom.T_ROOM, org.zhuyb.graphbatis.jooq.tables.pojos.TRoom.class);
    }

    /**
     * Create a new TRoomDao with an attached configuration
     */
    @Autowired
    public TRoomDao(Configuration configuration) {
        super(TRoom.T_ROOM, org.zhuyb.graphbatis.jooq.tables.pojos.TRoom.class, configuration);
    }

    @Override
    public Integer getId(org.zhuyb.graphbatis.jooq.tables.pojos.TRoom object) {
        return object.getRoomId();
    }

    /**
     * Fetch records that have <code>room_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TRoom> fetchRangeOfRoomId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TRoom.T_ROOM.ROOM_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>room_id IN (values)</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TRoom> fetchByRoomId(Integer... values) {
        return fetch(TRoom.T_ROOM.ROOM_ID, values);
    }

    /**
     * Fetch a unique record that has <code>room_id = value</code>
     */
    public org.zhuyb.graphbatis.jooq.tables.pojos.TRoom fetchOneByRoomId(Integer value) {
        return fetchOne(TRoom.T_ROOM.ROOM_ID, value);
    }

    /**
     * Fetch records that have <code>room_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TRoom> fetchRangeOfRoomName(String lowerInclusive, String upperInclusive) {
        return fetchRange(TRoom.T_ROOM.ROOM_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>room_name IN (values)</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TRoom> fetchByRoomName(String... values) {
        return fetch(TRoom.T_ROOM.ROOM_NAME, values);
    }
}
