/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables.daos;


import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.zhuyb.graphbatis.jooq.tables.TSubject;
import org.zhuyb.graphbatis.jooq.tables.records.TSubjectRecord;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Repository
public class TSubjectDao extends DAOImpl<TSubjectRecord, org.zhuyb.graphbatis.jooq.tables.pojos.TSubject, Integer> {

    /**
     * Create a new TSubjectDao without any configuration
     */
    public TSubjectDao() {
        super(TSubject.T_SUBJECT, org.zhuyb.graphbatis.jooq.tables.pojos.TSubject.class);
    }

    /**
     * Create a new TSubjectDao with an attached configuration
     */
    @Autowired
    public TSubjectDao(Configuration configuration) {
        super(TSubject.T_SUBJECT, org.zhuyb.graphbatis.jooq.tables.pojos.TSubject.class, configuration);
    }

    @Override
    public Integer getId(org.zhuyb.graphbatis.jooq.tables.pojos.TSubject object) {
        return object.getSubjectId();
    }

    /**
     * Fetch records that have <code>subject_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TSubject> fetchRangeOfSubjectId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TSubject.T_SUBJECT.SUBJECT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>subject_id IN (values)</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TSubject> fetchBySubjectId(Integer... values) {
        return fetch(TSubject.T_SUBJECT.SUBJECT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>subject_id = value</code>
     */
    public org.zhuyb.graphbatis.jooq.tables.pojos.TSubject fetchOneBySubjectId(Integer value) {
        return fetchOne(TSubject.T_SUBJECT.SUBJECT_ID, value);
    }

    /**
     * Fetch records that have <code>subject_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TSubject> fetchRangeOfSubjectName(String lowerInclusive, String upperInclusive) {
        return fetchRange(TSubject.T_SUBJECT.SUBJECT_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>subject_name IN (values)</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TSubject> fetchBySubjectName(String... values) {
        return fetch(TSubject.T_SUBJECT.SUBJECT_NAME, values);
    }
}
