/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables.daos;


import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.zhuyb.graphbatis.jooq.tables.TTeacherRoom;
import org.zhuyb.graphbatis.jooq.tables.records.TTeacherRoomRecord;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Repository
public class TTeacherRoomDao extends DAOImpl<TTeacherRoomRecord, org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom, Integer> {

    /**
     * Create a new TTeacherRoomDao without any configuration
     */
    public TTeacherRoomDao() {
        super(TTeacherRoom.T_TEACHER_ROOM, org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom.class);
    }

    /**
     * Create a new TTeacherRoomDao with an attached configuration
     */
    @Autowired
    public TTeacherRoomDao(Configuration configuration) {
        super(TTeacherRoom.T_TEACHER_ROOM, org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom.class, configuration);
    }

    @Override
    public Integer getId(org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom object) {
        return object.getTeacherRoomId();
    }

    /**
     * Fetch records that have <code>teacher_room_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom> fetchRangeOfTeacherRoomId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TTeacherRoom.T_TEACHER_ROOM.TEACHER_ROOM_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>teacher_room_id IN (values)</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom> fetchByTeacherRoomId(Integer... values) {
        return fetch(TTeacherRoom.T_TEACHER_ROOM.TEACHER_ROOM_ID, values);
    }

    /**
     * Fetch a unique record that has <code>teacher_room_id = value</code>
     */
    public org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom fetchOneByTeacherRoomId(Integer value) {
        return fetchOne(TTeacherRoom.T_TEACHER_ROOM.TEACHER_ROOM_ID, value);
    }

    /**
     * Fetch records that have <code>teacher_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom> fetchRangeOfTeacherId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TTeacherRoom.T_TEACHER_ROOM.TEACHER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>teacher_id IN (values)</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom> fetchByTeacherId(Integer... values) {
        return fetch(TTeacherRoom.T_TEACHER_ROOM.TEACHER_ID, values);
    }

    /**
     * Fetch records that have <code>room_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom> fetchRangeOfRoomId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TTeacherRoom.T_TEACHER_ROOM.ROOM_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>room_id IN (values)</code>
     */
    public List<org.zhuyb.graphbatis.jooq.tables.pojos.TTeacherRoom> fetchByRoomId(Integer... values) {
        return fetch(TTeacherRoom.T_TEACHER_ROOM.ROOM_ID, values);
    }
}
