/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.zhuyb.graphbatis.jooq.tables.*;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_ROOM_PRIMARY = Indexes0.T_ROOM_PRIMARY;
    public static final Index T_STUDENT_PRIMARY = Indexes0.T_STUDENT_PRIMARY;
    public static final Index T_SUBJECT_PRIMARY = Indexes0.T_SUBJECT_PRIMARY;
    public static final Index T_TEACHER_PRIMARY = Indexes0.T_TEACHER_PRIMARY;
    public static final Index T_TEACHER_ROOM_PRIMARY = Indexes0.T_TEACHER_ROOM_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_ROOM_PRIMARY = Internal.createIndex("PRIMARY", TRoom.T_ROOM, new OrderField[]{TRoom.T_ROOM.ROOM_ID}, true);
        public static Index T_STUDENT_PRIMARY = Internal.createIndex("PRIMARY", TStudent.T_STUDENT, new OrderField[]{TStudent.T_STUDENT.STUDENT_ID}, true);
        public static Index T_SUBJECT_PRIMARY = Internal.createIndex("PRIMARY", TSubject.T_SUBJECT, new OrderField[]{TSubject.T_SUBJECT.SUBJECT_ID}, true);
        public static Index T_TEACHER_PRIMARY = Internal.createIndex("PRIMARY", TTeacher.T_TEACHER, new OrderField[]{TTeacher.T_TEACHER.TEACHER_ID}, true);
        public static Index T_TEACHER_ROOM_PRIMARY = Internal.createIndex("PRIMARY", TTeacherRoom.T_TEACHER_ROOM, new OrderField[]{TTeacherRoom.T_TEACHER_ROOM.TEACHER_ROOM_ID}, true);
    }
}
