/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq;


import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.zhuyb.graphbatis.jooq.tables.*;
import org.zhuyb.graphbatis.jooq.tables.records.*;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code></code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TRoomRecord, Integer> IDENTITY_T_ROOM = Identities0.IDENTITY_T_ROOM;
    public static final Identity<TStudentRecord, Integer> IDENTITY_T_STUDENT = Identities0.IDENTITY_T_STUDENT;
    public static final Identity<TSubjectRecord, Integer> IDENTITY_T_SUBJECT = Identities0.IDENTITY_T_SUBJECT;
    public static final Identity<TTeacherRecord, Integer> IDENTITY_T_TEACHER = Identities0.IDENTITY_T_TEACHER;
    public static final Identity<TTeacherRoomRecord, Integer> IDENTITY_T_TEACHER_ROOM = Identities0.IDENTITY_T_TEACHER_ROOM;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TRoomRecord> KEY_T_ROOM_PRIMARY = UniqueKeys0.KEY_T_ROOM_PRIMARY;
    public static final UniqueKey<TStudentRecord> KEY_T_STUDENT_PRIMARY = UniqueKeys0.KEY_T_STUDENT_PRIMARY;
    public static final UniqueKey<TSubjectRecord> KEY_T_SUBJECT_PRIMARY = UniqueKeys0.KEY_T_SUBJECT_PRIMARY;
    public static final UniqueKey<TTeacherRecord> KEY_T_TEACHER_PRIMARY = UniqueKeys0.KEY_T_TEACHER_PRIMARY;
    public static final UniqueKey<TTeacherRoomRecord> KEY_T_TEACHER_ROOM_PRIMARY = UniqueKeys0.KEY_T_TEACHER_ROOM_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TRoomRecord, Integer> IDENTITY_T_ROOM = Internal.createIdentity(TRoom.T_ROOM, TRoom.T_ROOM.ROOM_ID);
        public static Identity<TStudentRecord, Integer> IDENTITY_T_STUDENT = Internal.createIdentity(TStudent.T_STUDENT, TStudent.T_STUDENT.STUDENT_ID);
        public static Identity<TSubjectRecord, Integer> IDENTITY_T_SUBJECT = Internal.createIdentity(TSubject.T_SUBJECT, TSubject.T_SUBJECT.SUBJECT_ID);
        public static Identity<TTeacherRecord, Integer> IDENTITY_T_TEACHER = Internal.createIdentity(TTeacher.T_TEACHER, TTeacher.T_TEACHER.TEACHER_ID);
        public static Identity<TTeacherRoomRecord, Integer> IDENTITY_T_TEACHER_ROOM = Internal.createIdentity(TTeacherRoom.T_TEACHER_ROOM, TTeacherRoom.T_TEACHER_ROOM.TEACHER_ROOM_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<TRoomRecord> KEY_T_ROOM_PRIMARY = Internal.createUniqueKey(TRoom.T_ROOM, "KEY_t_room_PRIMARY", TRoom.T_ROOM.ROOM_ID);
        public static final UniqueKey<TStudentRecord> KEY_T_STUDENT_PRIMARY = Internal.createUniqueKey(TStudent.T_STUDENT, "KEY_t_student_PRIMARY", TStudent.T_STUDENT.STUDENT_ID);
        public static final UniqueKey<TSubjectRecord> KEY_T_SUBJECT_PRIMARY = Internal.createUniqueKey(TSubject.T_SUBJECT, "KEY_t_subject_PRIMARY", TSubject.T_SUBJECT.SUBJECT_ID);
        public static final UniqueKey<TTeacherRecord> KEY_T_TEACHER_PRIMARY = Internal.createUniqueKey(TTeacher.T_TEACHER, "KEY_t_teacher_PRIMARY", TTeacher.T_TEACHER.TEACHER_ID);
        public static final UniqueKey<TTeacherRoomRecord> KEY_T_TEACHER_ROOM_PRIMARY = Internal.createUniqueKey(TTeacherRoom.T_TEACHER_ROOM, "KEY_t_teacher_room_PRIMARY", TTeacherRoom.T_TEACHER_ROOM.TEACHER_ROOM_ID);
    }
}
