/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq;


import org.zhuyb.graphbatis.jooq.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>t_room</code>.
     */
    public static final TRoom T_ROOM = TRoom.T_ROOM;

    /**
     * The table <code>t_student</code>.
     */
    public static final TStudent T_STUDENT = TStudent.T_STUDENT;

    /**
     * The table <code>t_subject</code>.
     */
    public static final TSubject T_SUBJECT = TSubject.T_SUBJECT;

    /**
     * The table <code>t_teacher</code>.
     */
    public static final TTeacher T_TEACHER = TTeacher.T_TEACHER;

    /**
     * The table <code>t_teacher_room</code>.
     */
    public static final TTeacherRoom T_TEACHER_ROOM = TTeacherRoom.T_TEACHER_ROOM;
}
