package org.zhuyb.graphbatis.entity;

import org.zhuyb.graphbatis.anno.QueryName;

import java.io.Serializable;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_room
 * <p>
 * If you want to modify
 * <p>
 * 1. checkout feature/gen
 * 2. mybatis-generator:generate
 * 3. commit -m 'your comment'
 * 4. push
 * 5. checkout your branch
 * 6. merge feature/gen
 */
@QueryName("findRooms")
public class Room implements Serializable {
    /**
     * t_room
     */
    private static final long serialVersionUID = 1L;
    /**
     *
     */
    private Integer roomId;
    /**
     *
     */
    private String roomName;

    private List<Student> students;

    private List<Teacher> teachers;

    private List<Subject> subjects;

    public List<Subject> getSubjects() {
        return subjects;
    }

    public void setSubjects(List<Subject> subjects) {
        this.subjects = subjects;
    }

    public List<Student> getStudents() {
        return students;
    }

    public void setStudents(List<Student> students) {
        this.students = students;
    }

    public List<Teacher> getTeachers() {
        return teachers;
    }

    public void setTeachers(List<Teacher> teachers) {
        this.teachers = teachers;
    }

    /**
     * @return room_id
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * @param roomId
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * @return room_name
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * @param roomName
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName == null ? null : roomName.trim();
    }
}