package org.zhuyb.graphbatis.entity;

import java.io.Serializable;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_subject
 * <p>
 * If you want to modify
 * <p>
 * 1. checkout feature/gen
 * 2. mybatis-generator:generate
 * 3. commit -m 'your comment'
 * 4. push
 * 5. checkout your branch
 * 6. merge feature/gen
 */
public class Subject implements Serializable {
    /**
     * t_subject
     */
    private static final long serialVersionUID = 1L;
    /**
     *
     */
    private Integer subjectId;
    /**
     *
     */
    private String subjectName;

    private List<Teacher> teachers;

    public List<Teacher> getTeachers() {
        return teachers;
    }

    public void setTeachers(List<Teacher> teachers) {
        this.teachers = teachers;
    }

    /**
     * @return subject_id
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * @param subjectId
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * @return subject_name
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * @param subjectName
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }
}