/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TRoom {

    private Integer roomId;
    private String roomName;

    public TRoom() {
    }

    public TRoom(TRoom value) {
        this.roomId = value.roomId;
        this.roomName = value.roomName;
    }

    public TRoom(
            Integer roomId,
            String roomName
    ) {
        this.roomId = roomId;
        this.roomName = roomName;
    }

    public Integer getRoomId() {
        return this.roomId;
    }

    public TRoom setRoomId(Integer roomId) {
        this.roomId = roomId;
        return this;
    }

    @Size(max = 50)
    public String getRoomName() {
        return this.roomName;
    }

    public TRoom setRoomName(String roomName) {
        this.roomName = roomName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TRoom other = (TRoom) obj;
        if (roomId == null) {
            if (other.roomId != null)
                return false;
        } else if (!roomId.equals(other.roomId))
            return false;
        if (roomName == null) {
            if (other.roomName != null)
                return false;
        } else if (!roomName.equals(other.roomName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.roomId == null) ? 0 : this.roomId.hashCode());
        result = prime * result + ((this.roomName == null) ? 0 : this.roomName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRoom (");

        sb.append(roomId);
        sb.append(", ").append(roomName);

        sb.append(")");
        return sb.toString();
    }
}
