/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TStudent {

    private Integer studentId;
    private Integer roomId;
    private String studentName;

    public TStudent() {
    }

    public TStudent(TStudent value) {
        this.studentId = value.studentId;
        this.roomId = value.roomId;
        this.studentName = value.studentName;
    }

    public TStudent(
            Integer studentId,
            Integer roomId,
            String studentName
    ) {
        this.studentId = studentId;
        this.roomId = roomId;
        this.studentName = studentName;
    }

    public Integer getStudentId() {
        return this.studentId;
    }

    public TStudent setStudentId(Integer studentId) {
        this.studentId = studentId;
        return this;
    }

    public Integer getRoomId() {
        return this.roomId;
    }

    public TStudent setRoomId(Integer roomId) {
        this.roomId = roomId;
        return this;
    }

    @Size(max = 50)
    public String getStudentName() {
        return this.studentName;
    }

    public TStudent setStudentName(String studentName) {
        this.studentName = studentName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TStudent other = (TStudent) obj;
        if (studentId == null) {
            if (other.studentId != null)
                return false;
        } else if (!studentId.equals(other.studentId))
            return false;
        if (roomId == null) {
            if (other.roomId != null)
                return false;
        } else if (!roomId.equals(other.roomId))
            return false;
        if (studentName == null) {
            if (other.studentName != null)
                return false;
        } else if (!studentName.equals(other.studentName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.studentId == null) ? 0 : this.studentId.hashCode());
        result = prime * result + ((this.roomId == null) ? 0 : this.roomId.hashCode());
        result = prime * result + ((this.studentName == null) ? 0 : this.studentName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TStudent (");

        sb.append(studentId);
        sb.append(", ").append(roomId);
        sb.append(", ").append(studentName);

        sb.append(")");
        return sb.toString();
    }
}
