/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TSubject {

    private Integer subjectId;
    private String subjectName;

    public TSubject() {
    }

    public TSubject(TSubject value) {
        this.subjectId = value.subjectId;
        this.subjectName = value.subjectName;
    }

    public TSubject(
            Integer subjectId,
            String subjectName
    ) {
        this.subjectId = subjectId;
        this.subjectName = subjectName;
    }

    public Integer getSubjectId() {
        return this.subjectId;
    }

    public TSubject setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
        return this;
    }

    @Size(max = 50)
    public String getSubjectName() {
        return this.subjectName;
    }

    public TSubject setSubjectName(String subjectName) {
        this.subjectName = subjectName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TSubject other = (TSubject) obj;
        if (subjectId == null) {
            if (other.subjectId != null)
                return false;
        } else if (!subjectId.equals(other.subjectId))
            return false;
        if (subjectName == null) {
            if (other.subjectName != null)
                return false;
        } else if (!subjectName.equals(other.subjectName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.subjectId == null) ? 0 : this.subjectId.hashCode());
        result = prime * result + ((this.subjectName == null) ? 0 : this.subjectName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TSubject (");

        sb.append(subjectId);
        sb.append(", ").append(subjectName);

        sb.append(")");
        return sb.toString();
    }
}
