/*
 * This file is generated by jOOQ.
 */
package org.zhuyb.graphbatis.jooq.tables.pojos;


import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TTeacherRoom {

    private Integer teacherRoomId;
    private Integer teacherId;
    private Integer roomId;

    public TTeacherRoom() {
    }

    public TTeacherRoom(TTeacherRoom value) {
        this.teacherRoomId = value.teacherRoomId;
        this.teacherId = value.teacherId;
        this.roomId = value.roomId;
    }

    public TTeacherRoom(
            Integer teacherRoomId,
            Integer teacherId,
            Integer roomId
    ) {
        this.teacherRoomId = teacherRoomId;
        this.teacherId = teacherId;
        this.roomId = roomId;
    }

    public Integer getTeacherRoomId() {
        return this.teacherRoomId;
    }

    public TTeacherRoom setTeacherRoomId(Integer teacherRoomId) {
        this.teacherRoomId = teacherRoomId;
        return this;
    }

    public Integer getTeacherId() {
        return this.teacherId;
    }

    public TTeacherRoom setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
        return this;
    }

    public Integer getRoomId() {
        return this.roomId;
    }

    public TTeacherRoom setRoomId(Integer roomId) {
        this.roomId = roomId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TTeacherRoom other = (TTeacherRoom) obj;
        if (teacherRoomId == null) {
            if (other.teacherRoomId != null)
                return false;
        } else if (!teacherRoomId.equals(other.teacherRoomId))
            return false;
        if (teacherId == null) {
            if (other.teacherId != null)
                return false;
        } else if (!teacherId.equals(other.teacherId))
            return false;
        if (roomId == null) {
            if (other.roomId != null)
                return false;
        } else if (!roomId.equals(other.roomId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.teacherRoomId == null) ? 0 : this.teacherRoomId.hashCode());
        result = prime * result + ((this.teacherId == null) ? 0 : this.teacherId.hashCode());
        result = prime * result + ((this.roomId == null) ? 0 : this.roomId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TTeacherRoom (");

        sb.append(teacherRoomId);
        sb.append(", ").append(teacherId);
        sb.append(", ").append(roomId);

        sb.append(")");
        return sb.toString();
    }
}
