package org.zhuyb.graphbatis.entity;

import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_student
 * <p>
 * If you want to modify
 * <p>
 * 1. checkout feature/gen
 * 2. mybatis-generator:generate
 * 3. commit -m 'your comment'
 * 4. push
 * 5. checkout your branch
 * 6. merge feature/gen
 */
public class Student implements Serializable {
    /**
     * t_student
     */
    private static final long serialVersionUID = 1L;
    /**
     *
     */
    private Integer studentId;
    /**
     *
     */
    private Integer roomId;
    /**
     *
     */
    private String studentName;

    /**
     * @return student_id
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * @param studentId
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * @return room_id
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * @param roomId
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * @return student_name
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * @param studentName
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }
}